// <auto-generated />
namespace InvoiceManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dodane_pola_wartosc_do_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodane_pola_wartosc_do_product));
        
        string IMigrationMetadata.Id
        {
            get { return "202101061548268_dodane_pola_wartosc_do_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
